Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-22.04"

  #IP depends of your network
  config.vm.network "public_network", ip: "192.168.0.30"
  config.vm.network "forwarded_port", guest: 4243, host: 4243

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
    vb.name="vmAgentDocker"
  end
  
  config.vm.provision "shell", inline: <<-SHELL
    sudo root
    #Mise a jour du systeme
    apt-get update

    #Installation de docker
    wget -O get-docker.sh https://get.docker.com/
    sh get-docker.sh

  SHELL
end
