Vagrant.configure("2") do |config|
  #means that the hypervisor is virtualbox
  config.vm.box = "bento/ubuntu-22.04"

  # NOTE: This will enable public access to the opened port
  config.vm.network "forwarded_port", guest: 80, host: 8080 # jenkins

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
    vb.name="vmMaster"
  end

  config.vm.provision "shell", inline: <<-SHELL
    su root
    apt-get update

    wget -O /usr/share/keyrings/jenkins-keyring.asc \
    https://pkg.jenkins.io/debian/jenkins.io-2023.key
    echo "deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc]" \
    https://pkg.jenkins.io/debian binary/ | sudo tee \
    /etc/apt/sources.list.d/jenkins.list > /dev/null

    apt-get update
    apt-get install -y fontconfig openjdk-17-jre
    apt-get install -y jenkins

    jenkins --httpPort=80
    
  SHELL
end
