Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-22.04"

  config.vm.network "forwarded_port", guest: 8080, host: 8090
  #IP depends of your network
  config.vm.network "private_network", ip: "192.168.33.10"
  
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
    vb.name="vmServer"
  end

  config.vm.provision "shell", inline: <<-SHELL
    sudo root
    #Mise a jour du systeme et installation d'un jdk pour lancer le serveur
    apt-get update
    apt-get install -y openjdk-17-jdk

  SHELL
end
